#data:
#    source: some API
#    from: date
#    to: date
#    formatting: min | hour | day

# TEMP DATASET TO USE
data: ../EURUSD1m.csv

# RAW DATA PROCESSING
processing:
    resample: true
    time: D
    aggregate: {
        Open: first,
        High: max,
        Low: min,
        Close: last,
        Volume: sum
    }
    label:
        from: Close
        shift: 1

# FEATURE INJECTION
features:
    category: all
    window: 14

# TRAIN/TEST SPLITTING
splitting:
    train_split: 0.8
    validation_folds: 5

# MODEL ENSEMBLE
regression_ensemble:
    models:
        - linreg:
        - lstm:
            morph:
                  window: 4
                  batch: 30
            layers:
                - lstm:
                    value: 120
                    activation: relu
                - dropout:
                    value: 0.15
                - dense:
                    value: 50
                    activation: relu
                - dense:
                    value: 1
            epochs: 7
            batch: 8
            validation: 25
            loss: mean_squared_error
            optimizer: rmsprop
        - tcn:
            morph:
                window: 4
                batch: 30
            layers:
                - tcn:      # Default values included to show what can be customized
                    nb_filters: 64
                    nb_stacks: 1
                    dilations: [1, 2, 4, 8, 16, 32]
                    padding: 'causal'
                    use_skip_connections: False
                    dropout_rate: 0.10
                    return_sequences: False
                    activation: 'relu'
                - dropout:
                    value: 0.05
                - dense:
                    value: 50
                    activation: relu
                - dense:
                      value: 1
            epochs: 3
            batch: 4
            validation: 40
            loss: mean_squared_error
            optimizer: adam
        - svc:
            split:
                train: 0.6
                test: 0.2
                validation: 0.2
classification_ensemble:
    decision:
        name: quantile
        upper: 0.75
        lower: 0.25
        #name: threshold
        #value: 0.003
    models:
        - logreg:
        - rand_forest: