---
data: pftest.csv # path_to_data.csv
investment_capital: 100 # INTEGER value. represents euro/dollar amount.
investing_profiles:
  profile_1:
    buy_weight: 1 # Value between 0 - 1
    sell_weight: 1 # Value between 0 - 1
  profile_2:
    buy_weight: 0.8 # Value between 0 - 1
    sell_weight: 0.8 # Value between 0 - 1
  profile_3:
    buy_weight: 0.6 # Value between 0 - 1
    sell_weight: 0.6 # Value between 0 - 1
  profile_4:
    buy_weight: 0.4 # Value between 0 - 1
    sell_weight: 0.4 # Value between 0 - 1
  profile_5:
    buy_weight: 0.2 # Value between 0 - 1
    sell_weight: 0.2 # Value between 0 - 1
...